#ifndef __config__
#define __config__

/**
@file
Subclass of app, which is generated by wxFormBuilder.
*/

#include "config_base.h"

//// end generated include

/** Implementing app */
class CONFIG : public CONFIG_BASE
{
  public:
    CONFIG(wxWindow *parent);
    //// end generated class members
};

#endif // __config__
